final_space = true
# shell_integration = true
enable_cursor_positioning = true
version = 4

[upgrade]
notice = true

[[blocks]]
type = "prompt"
alignment = "left"

[[blocks.segments]]
type = "path"
style = "plain"
template = "{{ .Path }} "

[blocks.segments.options]
style = "full"
cycle = [ "lightBlue", "blue", "magenta", "lightMagenta", "magenta", "blue" ]
cycle_folder_separator = true

[[blocks]]
type = "prompt"
alignment = "right"
filler = "<darkGray>·"
overflow = "hide"
force = true

[[blocks.segments]]
type = "time"
style = "plain"

[[blocks]]
type = "prompt"
newline = true
alignment = "left"

[[blocks.segments]]
type = "text"
template = "{{ if eq .Code 0 }}{{ else }}<red>{{ end }}❯"
style = "plain"

[transient_prompt]
foreground = "darkGray"
template = """
<darkGray>\
················································································\
\u001b[1G\
<lightBlue>{{ .Folder }} \
\u001b[72G \
<default>{{ .Segments.Time.CurrentDate | date .Segments.Time.Format }}\
\n{{ if eq .Code 0 }}<default>{{ else }}<red>{{ end }}❯ <darkGray>\
"""

[secondary_prompt]
template="❯ "
